<a href="https://colab.research.google.com/github/tarik19x/Deep-Neural-Networks-with-PyTorch/blob/main/Multiple%20Input%20Output%20Linear%20Regression/Linear_Regression_Multiple_Outputs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DL0110EN-SkillsNetwork/Template/module%201/images/IDSNlogo.png" width="300" alt="cognitiveclass.ai logo"  />
</center>


In [1]:
!nvidia-smi

Thu Mar  4 04:25:21 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.39       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   68C    P8    12W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

<h2>Objective</h2><ul><li> How to make a prediction using multiple samples.</li></ul> 


# Table of Contents

In this lab, we will  review how to make a prediction for Linear Regression with Multiple Output. 

<div class="alert alert-block alert-info" style="margin-top: 20px">

<li><a href="#ref2">Build Custom Modules </a></li>

<br>
<p></p>
Estimated Time Needed: <strong>15 min</strong>
</div>

<hr>


<a id="ref1"></a>

<h2 align=center>Class Linear  </h2>


In [2]:
from torch import nn
import torch

Set the random seed:


In [4]:
torch.manual_seed(1)

Set the random seed:


In [5]:
class linear_regression(nn.Module):
    def __init__(self,input_size,output_size):
        super(linear_regression,self).__init__()
        self.linear=nn.Linear(input_size,output_size)
    def forward(self,x):
        yhat=self.linear(x)
        return yhat

In [13]:
torch.tensor([1.0])

tensor([1.])

create a linear regression  object, as our input and output will be two we set the parameters accordingly 


In [56]:
model=linear_regression(4,5)

# model(torch.tensor([1.0]))
model.state_dict()

OrderedDict([('linear.weight', tensor([[ 0.2555,  0.1869,  0.4257, -0.3410],
                      [ 0.0043, -0.1477, -0.2797, -0.2813],
                      [ 0.1260,  0.0523, -0.2552, -0.3524],
                      [-0.4143,  0.4900, -0.0852, -0.1156],
                      [-0.1839, -0.2501, -0.4573, -0.2935]])),
             ('linear.bias',
              tensor([ 0.3056,  0.1096, -0.1764, -0.1890,  0.3194]))])

we can use the diagram to represent the model or object 


<img src = "https://ibm.box.com/shared/static/icmwnxru7nytlhnq5x486rffea9ncpk7.png" width = 600, align = "center">


we can see the parameters 


In [64]:
list(model.parameters())


[Parameter containing:
 tensor([[ 0.2555,  0.1869,  0.4257, -0.3410],
         [ 0.0043, -0.1477, -0.2797, -0.2813],
         [ 0.1260,  0.0523, -0.2552, -0.3524],
         [-0.4143,  0.4900, -0.0852, -0.1156],
         [-0.1839, -0.2501, -0.4573, -0.2935]], requires_grad=True),
 Parameter containing:
 tensor([ 0.3056,  0.1096, -0.1764, -0.1890,  0.3194], requires_grad=True)]

we can create a tensor with two rows representing one sample of data


In [61]:
x=torch.tensor([[1.0,3.9,2.7,0],[3.9,2.7,1.8,2],[3.9,2.7,10.8,0]])

In [62]:
x.shape

torch.Size([3, 4])

we can make a prediction 


In [63]:
yhat=model(x)
yhat.shape

torch.Size([3, 5])

each row in the following tensor represents a different sample 


In [26]:
X=torch.tensor([[1.0],
                [1.0],
                [3.0]])

In [25]:
X.shape

torch.Size([3, 1])

we can make a prediction using multiple samples 


In [27]:
Yhat=model(X)
Yhat.shape

torch.Size([3, 10])

the following figure represents the operation, where the red and blue  represents the different parameters, and the different shades of green represent  different samples.


 <img src = "https://ibm.box.com/shared/static/768cul6pj8hc93uh9ujpajihnp8xdukx.png" width = 600, align = "center">


<a href="https://dataplatform.cloud.ibm.com/registration/stepone?context=cpdaas&apps=data_science_experience,watson_machine_learning"><img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DL0110EN-SkillsNetwork/Template/module%201/images/Watson_Studio.png"/></a>


# About the Authors:

 [Joseph Santarcangelo](https://www.linkedin.com/in/joseph-s-50398b136?cm_mmc=Email_Newsletter-_-Developer_Ed%2BTech-_-WW_WW-_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-DL0110EN-SkillsNetwork-20647811&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ&cm_mmc=Email_Newsletter-_-Developer_Ed%2BTech-_-WW_WW-_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-DL0110EN-SkillsNetwork-20647811&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ) has a PhD in Electrical Engineering, his research focused on using machine learning, signal processing, and computer vision to determine how videos impact human cognition. Joseph has been working for IBM since he completed his PhD.

Other contributors: [Michelle Carey](https://www.linkedin.com/in/michelleccarey?cm_mmc=Email_Newsletter-_-Developer_Ed%2BTech-_-WW_WW-_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-DL0110EN-SkillsNetwork-20647811&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ) 


## Change Log

| Date (YYYY-MM-DD) | Version | Changed By | Change Description                                          |
| ----------------- | ------- | ---------- | ----------------------------------------------------------- |
| 2020-09-23        | 2.0     | Shubham    | Migrated Lab to Markdown and added to course repo in GitLab |


## <h3 align="center"> © IBM Corporation 2020. All rights reserved. <h3/>
